#version of docker compose
version: '3'
services:
  mysqlserver:
    image: mysql:8.0.28
    container_name: mysql-cont
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=guest
      - MYSQL_PASSWORD=guest
  rabbitmq:
    image: rabbitmq:3.9.14-management
    hostname: localhost
    container_name: rabbitmq-cont
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest




