#version of docker compose
version: '3'

services:
  mysql-service:
    image: mysql:8.0.28
    container_name: mysql-service
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=guest
      - MYSQL_PASSWORD=guest
    networks:
      es_net:
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./relational/docker-script/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
  rabbitmq-service:
    image: rabbitmq:3.9.14-management
    hostname: localhost
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      es_net:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672/" ]
      interval: 5s
      timeout: 5s
      retries: 20
  elasticsearch-service:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch-service
    environment:
      - node.name=es-node-1
      - discovery.type=single-node
      - cluster.name=es-data-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      # - xpack.security.enabled='false'
      # - xpack.monitoring.enabled='false'
      # - xpack.watcher.enabled='false'
      # - xpack.ml.enabled='false'
      # - http.cors.enabled='true'
      # - http.cors.allow-origin="*"
      # - http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE
      # - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type, Content-Length
      - logger.level:debug
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      es_net:
  kibana-service:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana
    environment:
      SERVER_NAME: 127.0.0.1
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      # XPACK_GRAPH_ENABLED: false
      # XPACK_ML_ENABLED: false
      # XPACK_REPORTING_ENABLED: false
      # XPACK_SECURITY_ENABLED: false
      # XPACK_WATCHER_ENABLED: false
    ports:
      - "5601:5601"
    networks:
      - es_net
    depends_on:
      - elasticsearch-service
    restart: "unless-stopped"
  elastic-service:
    build:
      context: elastic
      dockerfile: Dockerfile
    image: elasticservice:latest
    container_name: elastic-service
    networks:
      es_net:
    depends_on:
      mysql-service:
        condition: service_healthy
      rabbitmq-service:
        condition: service_healthy

  relational-service:
    build:
      context: relational
      dockerfile: Dockerfile
    image: relationalservice:latest
    container_name: relational-service
    networks:
      es_net:
    depends_on:
      mysql-service:
        condition: service_healthy
      rabbitmq-service:
        condition: service_healthy

volumes:
  es_volume:
    driver: local
  mysql_volume: { }


networks:
  es_net: